spring.application.name=swifttradeauthservice
# ===============================
# Spring DATASOURCE (PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/swift_trade_db?currentSchema=auth_schema
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# ===============================
# Server port (optional)
# ===============================
server.port=8081

# ===============================
# Logging (optional)
# ===============================
logging.level.org.hibernate.SQL=DEBUG